Cache the tarballs in pacote
npm/pacote pull request #74
Opened 2021-04-01 06:30 UTC by mjsir911

Tell `fetch` not to cache it's downloaded tarballs, leave that to us

Not sure the implications of changing the return type of _istream / adding a `cacache` to the end of the pipe, too unfamiliar with streams

Fixes #73 & Fixes npm/cli#2160

Also see npm/cli#2976 for my first attempt & some discussions as to how we got here.

2021-04-11 08:54 UTC, ttloves2 commented on lib/fetcher.js
> +    return stream.on('error', er => istream.emit('error', er)).pipe(istream).pipe(cstream)
nah

2021-04-13 15:28 UTC, isaacs commented on lib/fetcher.js
> +    return stream.on('error', er => istream.emit('error', er)).pipe(istream).pipe(cstream)
Yeah, I think this should almost certainly be `return new Pipeline(stream, istream, cstream)`

2021-04-13 15:30 UTC, isaacs commented on lib/fetcher.js
> +    return stream.on('error', er => istream.emit('error', er)).pipe(istream).pipe(cstream)
Er, wait, no.  I think `cstream` might not be a Passthrough?

I'll pull this locally and poke at it a bit, sorry for the uninformed comment 😅

2021-04-13 15:33 UTC, isaacs commented
So, in principle, I think this is probably the right direction.  We still let mfh do the caching of everything other than tarballs, but explicitly cache tarballs in the single choke-point in the logical flow.

I'll pull locally and take a look now.  At the very least, it will need tests to assert that `file:` and other tarballs are being cached as expected.

Thanks for updating your use case information over in https://github.com/npm/cli/pull/2976#issuecomment-811511134  It's helpful to know the end goal, and that does make sense.  We may want to update `npm cache add <spec>` to take multiple specs and add them all, I don't think that would be too terrible of a CLI change, and would likely make your bash script quite a bit faster.

2021-04-13 17:29 UTC, isaacs requested changes
Marking as "request changes", but I have the required changes ready to land, so don't sweat it.  I'll open up a separate PR to review, and mark this as closed once that lands.

Thanks!

2021-04-13 18:14 UTC, isaacs commented
@mjsir911 Can you take a look at #75?

2021-04-15 18:13 UTC, isaacs commented
Closed in favor of #75

2021-04-15 18:13 UTC, closed without merging